"""Speech for any language, from Microsoft Edge's neural voices.

The browser's own speechSynthesis was the original source, but it can only
speak what the user's machine happens to have installed. On the development
machine here that is Korean and US English and nothing else, and even Chrome's
bundled network voices -- which do cover Chinese and Japanese -- have no
Vietnamese and no Thai. A tool whose whole claim is "any language" cannot have
its audio depend on which voice packs someone installed.

edge-tts needs no API key and costs nothing. Every clip is written to disk, so
shadowing a sentence fifty times makes exactly one request.
"""

import asyncio
import hashlib
import re
from pathlib import Path

import cache


class TTSError(Exception):
    """Speech could not be produced for this text."""


# Voices are named "<lang>-<REGION>-<Name>Neural". Anything else is either a
# typo in a profile or an attempt to steer the request somewhere it shouldn't
# go, and the value reaches a subprocess-free but still external service.
_VOICE_RE = re.compile(r"^[a-z]{2,3}(-[A-Za-z]{2,8})+Neural$")

# Long enough for a caption line; anything past it is a caller bug rather than
# something worth synthesizing.
MAX_CHARS = 1000

# Slow speech is generated by the voice itself rather than by slowing playback
# down in the browser. That distinction matters here more than it would for
# English: resampling audio drags Mandarin tone contours and Japanese pitch
# accent out of shape, so the learner would be copying a pronunciation that is
# audibly wrong. Asking the model to speak slowly keeps them intact.
SLOW_RATE = "-25%"


def _validate_voice(voice: str | None, prof: dict) -> str:
    """Only voices this language actually registered, never a caller-supplied one.

    The default is the FIRST voice in the profile, matching what the client
    preselects in its toggle. Taking it from a set instead would be arbitrary
    and could differ between runs, quietly filling the cache with clips in a
    voice nobody chose.
    """
    registered = list(prof["voices"].values())
    if not voice:
        return registered[0]
    if voice in registered:
        return voice
    raise TTSError(f"Voice {voice!r} is not registered for {prof['name']}.")


def _synthesize(text: str, voice: str, path: Path, slow: bool = False) -> None:
    if not _VOICE_RE.match(voice):
        raise TTSError(f"Malformed voice name: {voice!r}")
    try:
        import edge_tts
    except ImportError as exc:  # pragma: no cover - depends on install state
        raise TTSError(
            "edge-tts is not installed. Run: pip install -r requirements.txt"
        ) from exc

    # Written aside and moved into place, so a failed or half-finished download
    # can never be picked up later as a valid cached clip.
    tmp = path.with_suffix(".part")
    rate = SLOW_RATE if slow else "+0%"

    async def run():
        await edge_tts.Communicate(text, voice, rate=rate).save(str(tmp))

    try:
        # The routes are sync `def`, so FastAPI runs them on a worker thread
        # with no event loop of its own -- asyncio.run is safe here, and would
        # not be inside an async route.
        asyncio.run(run())
    except Exception as exc:
        tmp.unlink(missing_ok=True)
        raise TTSError(f"Speech synthesis failed: {exc}") from exc

    if not tmp.exists() or tmp.stat().st_size == 0:
        tmp.unlink(missing_ok=True)
        raise TTSError("The speech service returned no audio.")
    tmp.replace(path)


def _prepare(text: str) -> str:
    text = " ".join((text or "").split())
    if not text:
        raise TTSError("There is nothing to speak.")
    if len(text) > MAX_CHARS:
        raise TTSError(f"Text is too long to speak ({len(text)} characters).")
    return text


def _variant(voice: str, slow: bool) -> str:
    """Voice plus speed, as one cache-path segment.

    Speed belongs in the key rather than being applied at playback: the two
    clips are genuinely different audio, and keeping both means toggling speed
    back and forth never costs a second request.
    """
    return f"{voice}-slow" if slow else voice


def sentence_audio(
    video_id: str, lang: str, idx: int, text: str, voice: str, prof: dict, slow: bool = False
) -> Path:
    """The clip for one transcript sentence, cached beside that video's JSON."""
    voice = _validate_voice(voice, prof)
    text = _prepare(text)
    directory = cache.video_dir(video_id, lang) / "tts"
    directory.mkdir(parents=True, exist_ok=True)
    # The text is in the key as well as the index: re-segmenting renumbers
    # sentences, and a stale clip would then be played for the wrong line.
    digest = hashlib.sha1(text.encode("utf-8")).hexdigest()[:10]
    path = directory / f"{_variant(voice, slow)}_{idx}_{digest}.mp3"
    if not path.exists():
        _synthesize(text, voice, path, slow)
    return path


def word_audio(lang: str, text: str, voice: str, prof: dict, slow: bool = False) -> Path:
    """The clip for a word, phrase or example sentence, shared across videos.

    Kept outside the per-video dirs because 天気 sounds the same wherever it
    appears -- and hearing a word on its own, with its tone or pitch intact, is
    the thing a beginner needs most and the thing the video audio cannot give.
    """
    voice = _validate_voice(voice, prof)
    text = _prepare(text)
    directory = cache.CACHE_ROOT / "_words" / lang / _variant(voice, slow)
    directory.mkdir(parents=True, exist_ok=True)
    path = directory / f"{hashlib.sha1(text.encode('utf-8')).hexdigest()}.mp3"
    if not path.exists():
        _synthesize(text, voice, path, slow)
    return path


def available() -> bool:
    try:
        import edge_tts  # noqa: F401

        return True
    except ImportError:
        return False
